apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: health-envoyfilter
  namespace: istio-system
spec:
  # workloadSelector:
  #   labels:
  #     app: helloserver
  configPatches:
    # The first patch adds the lua filter to the listener/http connection manager
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "envoy.router"
    patch:
      operation: INSERT_BEFORE
      value: 
        name: envoy.lua
        typed_config:
          "@type": "type.googleapis.com/envoy.config.filter.http.lua.v2.Lua"
          inlineCode: |
            function envoy_on_request(request_handle)
              if request_handle:headers():get(":path") == "/" then
                request_handle:respond({[":status"] = "200"},"ok")
              end
            end
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: xff-envoy-config-envoyfilter
  namespace: istio-system
spec:
  workloadSelector:
    label:
      app: istio-ingressgateway-internal
  configPatches:
    # The first patch adds the lua filter to the listener/http connection manager
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
        portNumber: 443
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          use_remote_address: true
          xff_num_trusted_hops: 2